### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Johnny5X** [zeobviouslyfakeacc/ModLoaderInstaller#14]
I had this error while trying to patch the tld exe

java.nio.file.NoSuchFileException: X:\Users\User\Desktop\Saves\THE LONG DARK\UMOD\zipfstmp5157016044353645477.tmp
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
	at java.nio.file.Files.newByteChannel(Unknown Source)
	at java.nio.file.Files.createFile(Unknown Source)
	at java.nio.file.TempFileHelper.create(Unknown Source)
	at java.nio.file.TempFileHelper.createTempFile(Unknown Source)
	at java.nio.file.Files.createTempFile(Unknown Source)
	at com.sun.nio.zipfs.ZipFileSystem.createTempFileInSameDirectoryAs(ZipFileSystem.java:1094)
	at com.sun.nio.zipfs.ZipFileSystem.getTempPathForEntry(ZipFileSystem.java:839)
	at com.sun.nio.zipfs.ZipFileSystem.newFileChannel(ZipFileSystem.java:723)
	at com.sun.nio.zipfs.ZipPath.newFileChannel(ZipPath.java:747)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileChannel(ZipFileSystemProvider.java:271)
	at java.nio.channels.FileChannel.open(Unknown Source)
	at java.nio.channels.FileChannel.open(Unknown Source)
	at me.zeobviouslyfakeacc.modloaderinstaller.FileUtils.applyXOR(FileUtils.java:53)
	at me.zeobviouslyfakeacc.modloaderinstaller.Patcher.call(Patcher.java:46)
	at me.zeobviouslyfakeacc.modloaderinstaller.Patcher.call(Patcher.java:14)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by zeobviouslyfakeacc** [comment]
Hmm, that's strange. That shouldn't possibly be able to go wrong. I have three ideas that you could try.

First, make sure that your antivirus program isn't sandboxing the installer. Might be a good idea to turn it off for a few minutes.

Second, make sure Java is updated. You can run `java -version` in a command prompt (cmd) to figure out what version you're using and go to https://www.java.com/download/ to get the most recent version.

If both of these don't work, it might have something to do with there being spaces in the path to your install directory (even though this works fine for me ¯\\\_(ツ)_/¯). You could try renaming "THE LONG DARK" to "THE_LONG_DARK" or something similar and try running the installer again.

**Comment by Johnny5X** [comment]
Thanks for responding so quick,and you were right it was windows defender that prevented the patch 😃

**Comment by zeobviouslyfakeacc** [comment]
Ah, alright 😄 

Thanks for letting me know what fixed it. Closed 🎉
