### ISSUE TITLE
JAR Files won't open/Jarfix didn't help

### ISSUE THREAD

**Issue by squirminherman** [zeobviouslyfakeacc/ModLoaderInstaller#24]
So, I have tried every solution that I could find to remedy this but JAR files still will not open for me on Windows 10. Not sure what else I can do. Pretty frustrated as I am not a programmer and have no idea why it isn't working. I ran Jarfix which seemed to work. It told me that .jar files were registered successfully but it doesn't seem to have done anything.

**Comment by squirminherman** [comment]
And I tried using command prompt. Didn't work. I tried multiple directories to the same effect.

**Comment by squirminherman** [comment]
Here is what I am seeing when I run it through command prompt:

Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: C:\Users\Sam (The system cannot find the file specified)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at sun.net.www.protocol.jar.URLJarFile.<init>(Unknown Source)
        at sun.net.www.protocol.jar.URLJarFile.getJarFile(Unknown Source)
        at sun.net.www.protocol.jar.JarFileFactory.get(Unknown Source)
        at sun.net.www.protocol.jar.JarURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.jar.JarURLConnection.getInputStream(Unknown Source)
        at java.net.URL.openStream(Unknown Source)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2440)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3214)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3175)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3148)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3124)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3104)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3097)
        at me.zeobviouslyfakeacc.modloaderinstaller.MainApplication.start(MainApplication.java:14)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
        ... 1 more

**Comment by zeobviouslyfakeacc** [comment]
Heyo! Strange stuff!

First of all, are you using the native binary (ModLoaderInstaller-Windows-x64.zip) or just the multi-platform JAR file (ModLoaderInstaller.jar)?

Also, could you run `java -version` in a command prompt for me, and send me the version string it prints?

**Comment by squirminherman** [comment]
I downloaded and attempted using both. Here is the java version:
C:\Users\Sam!>java -version
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) Client VM (build 25.221-b11, mixed mode, sharing)

**Comment by zeobviouslyfakeacc** [comment]
I'm almost certain that the cause is that exclamation mark in your windows username. Seems like Java doesn't like that for some reason. ([Related Java bug database entry](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4523159))

It might help if you move the ModLoaderInstaller into a directory whose path doesn't contain any exclamation marks, and try to run it from there.

**Comment by squirminherman** [comment]
Apparently it's a known bug that the user name doesn't change for your files/folders even when you change it in settings... So, I'm stuck with that little annoyance. But, your suggestion worked and the installer opened! Thanks! However, now I can't locate where TLD is on C: because it's not the Steam version. No idea where it installed. FML

**Comment by zeobviouslyfakeacc** [comment]
> because it's not the Steam version

What version is it, then? If it's the Microsoft Store / XBox Crossplay version, you're out of luck - that's an UWP application, which we unfortunately can't mod. If it's the GOG or an ""unofficial"" version, you'll just have to figure out where tld.exe is by checking the path your shortcuts link to, or find the path of the running application in your task manager.

**Comment by squirminherman** [comment]
Drat. That would be the issue. Guess I will need to head over to a certain swarthy site and grab the GOG version. Thanks again for taking the time and helping me figure this out! Really appreciate it and I will let you know if I get it working.

**Comment by zeobviouslyfakeacc** [comment]
I think they stopped selling the game on GOG, unfortunately :/

Steam is probably the only reasonable option for now.

**Comment by squirminherman** [comment]
Full unofficial version it is then! I didn't want to buy the game again anyway haha.
